version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: infracost/cloud-pricing-api
    ports: 
        - 4000:4000
    environment:
      - MONGODB_URI=mongodb://db:27017/cloudPricing
    depends_on: [db]
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - infracost

  updater:
    profiles: ["updater"]
    build:
      context: .
      dockerfile: Dockerfile
    image: infracost/cloud-pricing-api
    environment:
      - MONGODB_URI=mongodb://db:27017/cloudPricing
    depends_on: [db]
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - infracost
    command: ["npm", "run", "update"]

  db:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
     - 27017:27017
    networks:
      - infracost
 
volumes:
  mongodb-data:

networks:
  infracost:
