version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
        - 4000:4000
    environment:
      - MONGODB_URI=mongodb://db:27017/cloudPricing
      - UPDATE_CLOUD_PROVIDER=Azure
    depends_on: [db]
    # volumes:
    #   - ./data:/usr/src/app/data
    networks:
      - infracost

  db:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
     - 27017:27017
    networks:
      - infracost
 
volumes:
  mongodb-data:


networks:
  infracost:
