version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4000:4000
    environment:
      - MONGODB_URI=mongodb://db:27017/cloudPricing
      - CLOUD_PROVIDER=AWS
    depends_on: [db]

  db:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
     - 27017:27017
 
volumes:
  mongodb-data: